create table customer_orders 
(
	order_id integer,
	customer_id integer,
	order_date date,
	order_amount integer
);

insert into customer_orders values
(1,100,cast('2022-01-01' as date),2000),(2,200,cast('2022-01-01' as date),2500),(3,300,cast('2022-01-01' as date),2100)
,(4,100,cast('2022-01-02' as date),2000),(5,400,cast('2022-01-02' as date),2200),(6,500,cast('2022-01-02' as date),2700)
,(7,100,cast('2022-01-03' as date),3000),(8,400,cast('2022-01-03' as date),1000),(9,600,cast('2022-01-03' as date),3000);

select * from customer_orders;
--write a query to print order_id, new customer and old/repeat customer on each day
with first_visit as 
	(select customer_id,
	min(order_date) as first_visit_date
	from customer_orders
	group by customer_id),
	visit_flag as
	(select c.*, f.first_visit_date,
	case when c.order_date = f.first_visit_date then 1 else 0 end as new_customer,
	case when c.order_date != f.first_visit_date then 1 else 0 end as repeat_customer
	from customer_orders c
	inner join first_visit f on f.customer_id = c.customer_id)
select order_date, 
sum(new_customer) as no_of_new_customer,
sum(repeat_customer) as no_of_repeat_customer
from visit_flag
group by order_date;

--OR

with first_visit as		
	(select customer_id,
	min(order_date) as first_visit_date
	from customer_orders
	group by customer_id)
select c.order_date, 
sum(case when c.order_date = f.first_visit_date then 1 else 0 end) as no_of_new_customer,
sum(case when c.order_date != f.first_visit_date then 1 else 0 end) as no_of_repeat_customer
from customer_orders c
inner join first_visit f on f.customer_id = c.customer_id
group by c.order_date;

--or

select a.order_date,
sum(Case when a.order_date = a.first_order_date then 1 else 0 end) as new_customer,
sum(Case when a.order_date != a.first_order_date then 1 else 0 end) as repeat_customer
from
	(select customer_id, order_date, 
	min(order_date) over(partition by customer_id) as first_order_date from customer_orders) a 
group by a.order_date;
select * from customer_orders;


---Assignment---
--write a query to find the revenue generated by new customer and repeat customer
with first_visit as		
	(select customer_id,
	min(order_date) as first_visit_date
	from customer_orders
	group by customer_id)
select c.order_date, 
sum(case when c.order_date = f.first_visit_date then 1 else 0 end) as no_of_new_customer,
sum(case when c.order_date != f.first_visit_date then 1 else 0 end) as no_of_repeat_customer,
sum(case when c.order_date = f.first_visit_date then order_amount else 0 end) as revenue_by_new_customer,
sum(case when c.order_date != f.first_visit_date then order_amount else 0 end) as revenue_by_repeat_customer
from customer_orders c
inner join first_visit f on f.customer_id = c.customer_id
group by c.order_date;
